version: '3.8'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3
        # [Choice] Install Node.js
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ../..:/workspaces:cached
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

